chore: post rewrite fixes
gominima/website pull request #12
Opened 2022-03-06 08:08 UTC by savioxavier

This PR updates/changes the following stuff:
- Updated styles and wording for multiple components
- Changed monospace font to Fira Code
- Fixed some responsiveness issues
- Added two new fonts: Open Sans and Cabin to override system default
	- These two were the best pairings for Montserrat I could find
- Fixed some unnecessary bolding of text
- Formatted and cleaned up some files

2022-03-06 08:10 UTC, savioxavier commented
@megatank58 Can I use FontAwesome to render icons? I know it's a huge library, but it was kind of tough to work with SVGs, and FontAwesome's font implementation is so much easier. Plus there is more than one icon in the site, and more icons might be added too for aesthetic purposes.

2022-03-06 08:12 UTC, megatank58 commented
Does font awesome only bundle the icons we use? if it doesn't bundles all icons then I'm fine with using it

2022-03-06 09:01 UTC, savioxavier commented
I was unable to resolve solid Font Awesome icons for some reason, got the Golang icon ready.

2022-03-06 09:06 UTC, megatank58 commented
Linter workflow is failing

2022-03-06 09:25 UTC, savioxavier commented
> Linter workflow is failing, lint the codebase

Fixed!

2022-03-06 09:27 UTC, megatank58 requested changes

2022-03-06 09:27 UTC, megatank58 commented on src/App.vue
> +	<MadeBy />
MadeBy component isn't imported here

2022-03-06 09:27 UTC, megatank58 commented on src/components/Install.vue
> +			`,
why does `package main` has so many tabs and why was trim removed

2022-03-06 09:28 UTC, megatank58 commented
just some things, rest looks good to me

2022-03-06 09:33 UTC, apoorvcodes commented
@savioxavier I don't like the fonts, too thin.

2022-03-06 09:55 UTC, savioxavier commented
> @savioxavier I don't like the fonts, too thin.

I just selected a few fonts in order to override the system defaults (it doesn't look too good on Android). I couldn't find any other better font combos for Montserrat, so I used Cabin and Open Sans. The font weight is the _default_ font weight, provided by all the fonts, but that could be adjusted later.

2022-03-08 08:50 UTC, savioxavier commented
@apoorvcodes Deleted the Cabin font, updated font widths to make them bold, and added Pacifico font to render the logo.

2022-03-08 09:16 UTC, megatank58 approved these changes

2022-03-08 14:16 UTC, merged